# syntax

In [2]:
# syntax can be executed by writing directly in the Command Line:
print("Divya, Deswal!")

Divya, Deswal!


# indentation

In [7]:
#Indentation refers to the spaces at the beginning of a code line.
if 10 > 2:
 print("ten is greater")

ten is greater


In [14]:
if 4 > 1:
 print(6)

6


# variables

In [15]:
#variables are created when you assign a value to it:
# It has no command for declaring a variable.
x=6
x

6

In [16]:
x=7
y=8
print(x,y)

7 8


In [18]:
x = 12
y = "Divya"
print(x)
print(y)

12
Divya


In [3]:
x = 12
y = """Divya"""
x
y

'Divya'

In [21]:
x = 12
y = "Divya"
x,y

(12, 'Divya')

In [24]:
x = 12
y = "Divya"
x*y

'DivyaDivyaDivyaDivyaDivyaDivyaDivyaDivyaDivyaDivyaDivyaDivya'

In [30]:
x, y, z = "Orange", "Banana", "Cherry"
print(x)
print(y)
print(z)

Orange
Banana
Cherry


In [31]:
x, y, z = "Orange", "Banana", "Cherry"
print(x,y,z)

Orange Banana Cherry


# string

In [32]:
#Strings are surrounded by either single quotation marks, or double quotation marks.
print("Divya")
print("I am a 'student'")
print('of "Msc Statistics"')

Divya
I am a 'student'
of "Msc Statistics"


## string array

In [35]:
a="Msc Statistics"
print(a[:])

Msc Statistics


## string slicing

In [36]:
a="Msc Statistics"
print(a[1:])

sc Statistics


In [37]:
a="Msc Statistics"
print(a[0:])

Msc Statistics


In [38]:
a="Msc Statistics"
print(a[:6])

Msc St


In [39]:
a="Msc Statistics"
print(a[-13:-9])

sc S


In [15]:
a="Msc Statistics"
print(a[::2])

McSaitc


In [6]:
print(len(a))

14


In [10]:
a=1,2,3,4,5,6,7,8,9
print(a[1::3])

(2, 5, 8)


In [16]:
a=1,2,3,4,5,6,7,8,9,10
print(a[1:9:1])

(2, 3, 4, 5, 6, 7, 8, 9)


## uppercase & lowercase

In [43]:
#The upper() method returns the string in upper case:
a="Msc Statistics"
print(a.upper())

MSC STATISTICS


In [44]:
#The lower() method returns the string in lower case:
a="Msc Statistics"
print(a.lower())

msc statistics


## remove whitespace

In [45]:
#Whitespace is the space before and/or after the actual text, and very often you want to remove this space.
#The strip() method removes any whitespace from the beginning or the end:
a="  Msc Statistics  "
print(a.strip())

Msc Statistics


## replace string and split string

In [47]:
#The replace() method replaces a string with another string:
a="Msc Statistics"
print(a.replace("Msc","Bsc"))

Bsc Statistics


In [23]:
#The split() method returns a list where the text between the specified separator becomes the list items.
d="divyade:swal:ad"
print(d.split(":"))

['divyade', 'swal', 'ad']


## string concatenation

In [57]:
#To concatenate, or combine, two strings you can use the + operator.
a="Divya"
b=" I am a student"
c=" of Msc Statistics"
d=a+b+c
d


'Divya I am a student of Msc Statistics'

In [59]:
a="Divya"
b=" I am a student"
c=" of Msc Statistics"
d=a+","+b+","+c
d

'Divya, I am a student, of Msc Statistics'

# string format

In [26]:
a="divya"
txt=f"my name is {a}"
print(txt)

my name is divya


## f string

In [29]:
# to specify a string as an f-string, simply put an f in front of the string literal, and add curly brackets {} as placeholders
#for variables and other operations.
a="divya"
b=21
txt=f'my name is {a} and i am {b} old'
print(txt)

my name is divya and i am 21 old


In [30]:
txt=f"{3*4}"
print(txt)

12


In [33]:
a="Divya"
b=21
txt=f'my name is {a.lower()} and i am {float(b)} old'
print(txt)

my name is divya and i am 21.0 old


## placeholders and modifiers

In [37]:
a="divya"
b=21.2
txt=f'my name is {a} and i am {b:.4f} old'
print(txt)

my name is divya and i am 21.2000 old


In [20]:
txt=f'value is {23*56}'
print(txt)

value is 1288


# string methods

In [22]:
#Upper case the first letter in this sentence:
txt = "i am from rohtak."
x = txt.capitalize()
print (x)

I am from rohtak.


In [23]:
txt = "5 is my lucky number ."
x = txt.capitalize()
print (x)

5 is my lucky number .


In [25]:
txt = "divya deswal"
x = txt.center(70)
print(x)

                             divya deswal                             


In [3]:
txt = "I am a Student."
print(txt.encode())


b'I am a Student.'


In [31]:
txt = "I am a Student."
x = txt.find("Student")
print(x)

7


In [3]:
txt = "I am a Student."
x = txt.endswith(".")
print(x)

True


In [4]:
txt = "I am a Student."
x = txt.index("Student")
print(x)

7


In [5]:
txt = "student 6"
x = txt.isalpha()
print(x)

False


In [7]:
txt = "welcome to my world."
x = txt.startswith("Hello")
print(x)

False


In [6]:
txt = "Student 123"
x = txt.isascii()
print(x)

True


In [8]:
txt = "I could eat bananas all day, bananas are my favorite fruit"
x = txt.rpartition("bananas")
print(x)

('I could eat bananas all day, ', 'bananas', ' are my favorite fruit')


In [42]:
a='1234'
print(a.isalnum())

True


In [49]:
a="webmok \"rohtak\" data science"
print(a)

webmok "rohtak" data science


# type function

In [1]:
x=6     #int
y=67.89 #float
z=5+2j  #complex
print(type(x))
print(type(y))
print(type(z))

<class 'int'>
<class 'float'>
<class 'complex'>


## int

In [2]:
#Int, or integer, is a whole number, positive or negative, without decimals, of unlimited length.
x = 9
y = 5667899
z = -678
print(type(x))
print(type(y))
print(type(z))

<class 'int'>
<class 'int'>
<class 'int'>


## float

In [3]:
#Float, or "floating point number" is a number, positive or negative, containing one or more decimals.
x = 9.10
y = 78.0
z = -45.345
print(type(x))
print(type(y))
print(type(z))

<class 'float'>
<class 'float'>
<class 'float'>


In [4]:
#Float can also be scientific numbers with an "e" to indicate the power of 10.
x = 35e3
y = 12E4
z = -87.7e100
print(type(x))
print(type(y))
print(type(z))

<class 'float'>
<class 'float'>
<class 'float'>


In [5]:
x = 35e3
x

35000.0

## complex

In [6]:
#Complex numbers are written with a "j" as the imaginary part:
x = 7+0j
y = 9j
z = 5-2j
print(type(x))
print(type(y))
print(type(z))

<class 'complex'>
<class 'complex'>
<class 'complex'>


# type conversion

In [12]:
#You can convert from one type to another with the int(), float(), and complex() methods:
x = 56    # int
#convert from int to float:
a = float(x)
print(a)
print(type(a))

56.0
<class 'float'>


In [13]:
y = 24.08  # float
#convert from float to int:
b = int(y)
print(b)
print(type(b))

24
<class 'int'>


In [18]:
z = 6   # int
#convert from int to complex:
c = complex(z)
print(c)
print(type(c))

(6+0j)
<class 'complex'>


# operators

In [2]:
#Operators are used to perform operations on variables and values.

## arithmetic operators

In [3]:
#Arithmetic operators are used with numeric values to perform common mathematical operations:
x = 53
y = 31
print(x + y)

84


In [5]:
x = 53
y = 31
print(f"the number is {x + y}")


the number is 84


In [6]:
x = 53
y = 31
print(x - y)

22


In [7]:
x = 53
y = 31
print(x * y)

1643


In [8]:
x = 53
y = 31
print(x / y)

1.7096774193548387


In [9]:
x = 53
y = 31
print(x % y)

22


In [10]:
x = 53
y = 31
print(x // y)

1


In [12]:
x = 3
y = 2
print(x ** y)

9


## assignment operator

In [3]:
x = 5
print(x)

5


In [5]:
x = 15
x += 3
print(x)

18


In [6]:
x = 15
x -= 3
print(x)

12


In [7]:
x = 15
x *= 3
print(x)

45


In [8]:
x = 15
x /= 3
print(x)

5.0


In [9]:
x = 15
x //= 3
print(x)

5


In [10]:
x = 15
x %= 3
print(x)

0


In [11]:
x = 15
x **= 3
print(x)

3375


## comparison operator

In [12]:
x = 20
y = 15
print(x == y)

False


In [13]:
x = 20
y = 15
print(x > y)

True


In [14]:
x = 20
y = 15
print(x < y)

False


In [15]:
x = 20
y = 15
print(x != y)

True


In [16]:
x = 20
y = 15
print(x >= y)

True


In [17]:
x = 20
y = 15
print(x <= y)

False


## logical operator

In [19]:
x = 25
print(x > 6 and x < 30)

True


In [20]:
x = 25
print(x > 6 and x < 10)

False


In [21]:
x = 25
print(x > 6 or x < 30)

True


In [22]:
x = 25
print(x > 6 or x < 10)

True


In [23]:
x = 25
print(not(x > 6 and x < 30))

False


## identity operator

In [31]:
x = [13, 45]
y = ["divya", "deswal"]
z = y
print(y is z)
print(x is y)
print(x == y)

True
False
False


In [32]:
x = [13, 45]
y = ["divya", "deswal"]
z = y
print(y is not z)
print(x is not y)
print(x != y)

False
True
True


## membership operator

In [33]:
x = ["divya", "deswal"]
print("divya" in x)

True


In [35]:
x = ["divya", "deswal"]
print("divu" in x)

False


In [37]:
x = ["divya", "deswal"]
print("divya" not in x)

False


In [38]:
x = ["divya", "deswal"]
print("dia" not in x)

True


# list

In [1]:
#List items are ordered, changeable, and allow duplicate values.
x = ["fruit", "veg", "toy"]
print(x)

['fruit', 'veg', 'toy']


In [2]:
#Allow duplicates
x = ["fruit", "veg", "toy","fruit", "veg", "toy"]
print(x)

['fruit', 'veg', 'toy', 'fruit', 'veg', 'toy']


In [3]:
x = ["fruit", "veg", "toy"]
print(len(x))

3


In [5]:
x = ["fruit", "veg", "toy"]
print(type(x))

<class 'list'>


## access list

In [6]:
x = ["fruit", "veg", "toy"]
print(x[0])

fruit


In [7]:
x = ["fruit", "veg", "toy"]
print(x[2])

toy


In [8]:
x = ["apple", "banana", "cherry", "orange", "kiwi", "melon", "mango"]
print(x[2:5])

['cherry', 'orange', 'kiwi']


In [11]:
x = ["apple", "banana", "cherry", "orange", "kiwi", "melon", "mango"]
print(x[-5:-1])

['cherry', 'orange', 'kiwi', 'melon']


In [12]:
x = ["apple", "banana", "cherry", "orange", "kiwi", "melon", "mango"]
print(x[2:])

['cherry', 'orange', 'kiwi', 'melon', 'mango']


In [13]:
x = ["apple", "banana", "cherry", "orange", "kiwi", "melon", "mango"]
print(x[:5])

['apple', 'banana', 'cherry', 'orange', 'kiwi']


In [15]:
x = ["apple", "banana", "cherry", "orange", "kiwi", "melon", "mango"]
print(x[:])

['apple', 'banana', 'cherry', 'orange', 'kiwi', 'melon', 'mango']


## change list

In [16]:
#To change the value of a specific item, refer to the index number:
a = ["msc", "bsc", "m.a"]
a[1] = "b.ed"
print(a)

['msc', 'b.ed', 'm.a']


In [17]:
a = ["msc", "bsc", "m.a"]
a[0] = "b.ed"
print(a)

['b.ed', 'bsc', 'm.a']


In [19]:
a = ["msc", "bsc", "m.a"]
a[1] = ["b.ed","m.ed"]
print(a)

['msc', ['b.ed', 'm.ed'], 'm.a']


In [20]:
a = ["msc", "bsc", "m.a"]
a[1:3] = ["b.ed","m.ed"]
print(a)

['msc', 'b.ed', 'm.ed']


In [21]:
a = ["msc", "bsc", "m.a"]
a[0:2] = ["b.ed","m.ed"]
print(a)

['b.ed', 'm.ed', 'm.a']


In [22]:
a = ["msc", "bsc", "m.a"]
a[1:2] = ["b.ed","m.ed"]
print(a)

['msc', 'b.ed', 'm.ed', 'm.a']


## add list

### insert items

In [23]:
a = [12, 24, 36]
a.insert(2, "water")
print(a) 

[12, 24, 'water', 36]


### append items

In [25]:
a = [12, 24, 36]
a.append("water")
print(a) 

[12, 24, 36, 'water']


### extend items

In [26]:
a = [12, 24, 36]
b = [48,60,72]
a.extend(b)
print(a) 

[12, 24, 36, 48, 60, 72]


In [27]:
a = [12, 24, 36]
b = [48,60,72]
b.extend(a)
print(b) 

[48, 60, 72, 12, 24, 36]


## remove list

### remove items

In [29]:
a = [12, 24, 36]
a.remove(24)
print(a) 

[12, 36]


### pop 

In [30]:
#The pop() method removes the specified index.
a = [12, 24, 36]
a.pop(2)
print(a) 

[12, 24]


In [32]:
a = [12, 24, 36]
a.pop(0)
print(a)

[24, 36]


In [33]:
a = [12, 24, 36]
a.pop()
print(a)

[12, 24]


### delete

In [39]:
#The del keyword also removes the specified index:
a = [12, 24, 36]
del a[1]
print(a)

[12, 36]


In [43]:
a = [12, 24, 36]
del a

In [44]:
a = [12, 24, 36]
del a[0]
print(a)

[24, 36]


### clear

In [45]:
# The list still remains, but it has no content.
a = [12, 24, 36]
a.clear()
print(a)

[]


## sort list

In [47]:
x = ["A","B","C","a","b","c"]  # ascending order
x.sort()
print(x)

['A', 'B', 'C', 'a', 'b', 'c']


In [49]:
x = ["A","B","C","a","b","c"]  # descending order
x.sort(reverse = True)
print(x)

['c', 'b', 'a', 'C', 'B', 'A']


In [50]:
x = [3,10,9,6,4,12]  # ascending order
x.sort()
print(x)

[3, 4, 6, 9, 10, 12]


In [51]:
x = [3,10,9,6,4,12]  # descending order
x.sort(reverse = True)
print(x)

[12, 10, 9, 6, 4, 3]


In [52]:
x = [3,10,9,6,4,12]  
x.reverse()
print(x)

[12, 4, 6, 9, 10, 3]


In [53]:
x = ["A","B","C","a","b","c"]  
x.sort(key = str.lower)
print(x)

['A', 'a', 'B', 'b', 'C', 'c']


## copy list

In [54]:
a = ["app", "banned", "chill"]
b = a.copy()
print(b)

['app', 'banned', 'chill']


In [58]:
a = ["app", "banned", "chill"]
c = [2,3,4]
b = a.copy()
print(c)

[2, 3, 4]


## join list

In [59]:
x = ["a", "b", "c"]
y = [1, 2, 3]
z = x + y
print(z)

['a', 'b', 'c', 1, 2, 3]


In [60]:
a = ["app", "banned", "chill"]
c = [2,3,4]
b = a + c
print(b)

['app', 'banned', 'chill', 2, 3, 4]


In [1]:
# input method

In [5]:
a="webmok rohtak"
y=a.encode("utf-16")
y

b'\xff\xfew\x00e\x00b\x00m\x00o\x00k\x00 \x00r\x00o\x00h\x00t\x00a\x00k\x00'

# tuple

In [2]:
#Tuples are used to store multiple items in a single variable.
#Tuple is one of 4 built-in data types in Python used to store collections of data, the other 3 are List, Set, and Dictionary, 
#all with different qualities and usage.
#A tuple is a collection which is ordered and unchangeable.
#Tuples are written with round brackets.

In [3]:
T = ("app", "banned", "chill")
print(T)

('app', 'banned', 'chill')


## tuple items

In [4]:
#Tuple items are ordered, unchangeable, and allow duplicate values.
T = ("app", "banned", "chill","app", "banned", "chill")
print(T)

('app', 'banned', 'chill', 'app', 'banned', 'chill')


In [5]:
T = ("app", "banned", "chill","app", "banned", "chill")
print(len(T))

6


In [6]:
T = ("app",)
print(type(T))
#NOT a tuple
T = ("app")
print(type(T))

<class 'tuple'>
<class 'str'>


## Tuple Items - Data Types

In [8]:
t1 = ("app", "banned", "chill")
t2 = (12, 3, 17, 29, 33)
t3 = (True, False, False)
print(type(t1))
print(type(t2))
print(type(t3))

<class 'tuple'>
<class 'tuple'>
<class 'tuple'>


In [9]:
t1 = ("app", "banned", "chill")
t2 = (12, 3, 17, 29, 33)
t3 = (True, False, False)
print(t1)
print(t2)
print(t3)

('app', 'banned', 'chill')
(12, 3, 17, 29, 33)
(True, False, False)


In [11]:
x1 = ("abc", 33, True, 40, "female")
print(x1)

('abc', 33, True, 40, 'female')


In [12]:
x = tuple(("abc", 33, True, 40, "female")) # note the double round-brackets
print(x)

('abc', 33, True, 40, 'female')


In [ ]:
#List is a collection which is ordered and changeable. Allows duplicate members.
#Tuple is a collection which is ordered and unchangeable. Allows duplicate members.
#Set is a collection which is unordered, unchangeable*, and unindexed. No duplicate members.
#Dictionary is a collection which is ordered** and changeable. No duplicate members.

## indexing or range items

In [13]:
x = ("abc", 33, True, 40, "female")
print(x[2])

True


In [14]:
x = ("abc", 33, True, 40, "female")
print(x[4])

female


In [15]:
x = ("abc", 33, True, 40, "female")
print(x[-3])

True


In [16]:
x = ("abc", 33, True, 40, "female")
print(x[2:5])

(True, 40, 'female')


In [17]:
x = ("abc", 33, True, 40, "female")
print(x[:6])

('abc', 33, True, 40, 'female')


In [19]:
x = ("abc", 33, True, 40, "female")
print(x[-4:-2])

(33, True)


In [32]:
x = ("abc", 33, True, 40, "female")
if "abc" in x :
 print("Yes, 'abc' is in the string value")

Yes, 'abc' is in the string value


In [36]:
x = ("abc", 33, True, 40, "female")
if 33 in x :
 print("Yes, 33 is in the int value")

Yes, 33 is in the int value


### change tuple values

In [37]:
#Once a tuple is created, you cannot change its values. Tuples are unchangeable, or immutable as it also is called.
x = ("web", "mok", "rohtak")
y = list(x)
y[1] = "place"
x = tuple(y)
print(x)

('web', 'place', 'rohtak')


### add items

In [14]:
#Since tuples are immutable, they do not have a built-in append() method, but there are other ways to add items to a tuple.
#1. Convert into a list: Just like the workaround for changing a tuple, you can convert it into a list, add your item(s), 
#and convert it back into a tuple.
x = (45, "banner", 67)
y = list(x)
y.append("female")
x = tuple(y)
print(x)

(45, 'banner', 67, 'female')


In [15]:
x = ("abc", "banner", "ert")
y = list(x)
y.append("female")
x = tuple(y)
print(x)

('abc', 'banner', 'ert', 'female')


In [7]:
x = (45, "banner", 67)
y = ("orange",)
x += y
print(x)

(45, 'banner', 67, 'orange')


### remove items

In [16]:
x = ("abc", "banner", "ert")
y = list(x)
y.remove("ert")
x = tuple(y)
print(x)

('abc', 'banner')


In [13]:
x = ("apple", "banner", "chill")
y = list(x)
y.remove("apple")
x = tuple(y)
print(x)

('banner', 'chill')


In [23]:
x = ("abc", "banner", "ert")
del x

### unpacking tuple

In [24]:
#When we create a tuple, we normally assign values to it. This is called "packing" a tuple:
x = (2, 3, 4)     #packing
print(x)

(2, 3, 4)


In [27]:
x = (2, 3, 4)   #unpacking
(green, yellow, red) = x
print(green)
print(yellow)
print(red)

2
3
4


In [30]:
x = (2,4)   #unpacking
(green, yellow, *red) = x
print(green)
print(yellow)
print(red)

2
4
[]


In [32]:
x = (2, 3, 4)   #unpacking
(green, *red) = x
print(green)
print(red)

2
[3, 4]


In [33]:
x = (2, 3, 4)   #unpacking
(green, *red) = x
print(green)
print(yellow)
print(red)

2
4
[3, 4]


In [34]:
x = (2, 3, 4, 5, 6, 7, 8)   #unpacking
(green, *yellow, red) = x
print(green)
print(yellow)
print(red)

2
[3, 4, 5, 6, 7]
8


### join tuples

In [35]:
t1 = ("abc", "def" , "ghi")   # add tuples
t2 = (11, 22, 33)
t3 = t1 + t2
print(t3)

('abc', 'def', 'ghi', 11, 22, 33)


In [37]:
t1 = ("abc", "def" , "ghi")   # multiply tuples
t2 = t1*2
print(t2)

('abc', 'def', 'ghi', 'abc', 'def', 'ghi')


In [39]:
t2 = (11, 22, 33)
t3 = t2*3
print(t3)

(11, 22, 33, 11, 22, 33, 11, 22, 33)


# Set

In [1]:
# Set items are unordered, unchangeable, and do not allow duplicate values.
t1 = {"abc", "def" , "ghi"}
print(t1)


{'def', 'ghi', 'abc'}


In [2]:
# Duplicates Not Allowed
# Sets cannot have two items with the same value.
t1 = {"abc", "def" , "ghi", "abc", "def"}
print(t1)

{'def', 'ghi', 'abc'}


In [3]:
t1 = {"abc", "def" , "ghi"}
print(len(t1))


3


In [4]:
t1 = {"abc", "def" , "ghi"}
print(type(t1))

<class 'set'>


## access items

In [5]:
s = {"abc", "ert", 66}
for x in s:
  print(x)

66
ert
abc


In [6]:
s = {"abc", "ert", 66}
print("abc" in s)

True


In [7]:
s = {"abc", "ert", 66}
print("abc" not in s)

False


## add items

In [8]:
s = {"abc", "ert", 66}
s.add(87)
print(s)

{66, 'ert', 87, 'abc'}


In [10]:
s = {"abc", "ert", 66}
t = {"rtk", "urf"}
s.update(t)
print(s)

{66, 'rtk', 'abc', 'urf', 'ert'}


### add any iterable

In [11]:
# The object in the update() method does not have to be a set, it can be any iterable object (tuples, lists, dictionaries etc.).
s = {"abc", "bfg", 67}
t = ["ert", 87]
s.update(t)
print(s)

{'abc', 67, 'bfg', 87, 'ert'}


In [14]:
s = ["abc", "bfg", 67]
t = {"ert", 87}
t.update(s)
print(t)

{67, 'bfg', 87, 'abc', 'ert'}


## remove items

In [16]:
# To remove an item in a set, use the remove(), or the discard() method.
s = {"abc", "ert", 66}
s.remove(66)
print(s)

{'ert', 'abc'}


In [17]:
s = {"abc", "ert", 66}
s.remove(87)
print(s)

KeyError: 87

In [18]:
s = {"abc", "ert", 66}
s.discard(66)
print(s)

{'ert', 'abc'}


In [19]:
s = {"abc", "ert", 66}
s.discard(87)
print(s)

{66, 'ert', 'abc'}


In [22]:
s = {"abc", "btr", "cher"}
s.pop()
print(s)

{'btr', 'abc'}


In [23]:
s = {"abc", "btr", "cher"}
s.clear()
print(s)

set()


In [26]:
s = {"abc", "btr", "cher"}
del s

## join sets

#### union

In [41]:
s1 = {"a", "b", "c", "d"}
s2 = {1, 2, 3}
s3 = s1.union(s2)
print(s3)

{1, 2, 'd', 'b', 'c', 3, 'a'}


In [28]:
s1 = {"a", "b", "c", "d"}
s2 = {1, 2, 3}
s3 = s1|s2
print(s3)

{1, 2, 'd', 'b', 'c', 3, 'a'}


In [29]:
s1 = {"a", "b", "c"}
s2 = {1, 2, 3}
s3 = {"Jo", "El"}
s4 = {"avb", "ban", "cher"}
s5 = s1.union(s2, s3, s4)
print(s5)

{1, 2, 'c', 'b', 3, 'ban', 'cher', 'a', 'Jo', 'avb', 'El'}


In [31]:
s1 = {"a", "b", "c"}
s2 = {1, 2, 3}
s3 = {"Jo", "El"}
s4 = {"avb", "ban", "cher"}
s5 = s1|s2|s3|s4
print(s5)

{1, 2, 'c', 'b', 3, 'ban', 'cher', 'a', 'Jo', 'avb', 'El'}


In [35]:
# The union() method allows you to join a set with other data types, like lists or tuples.
x = {"a", "b", "c"}
y = (1, 2, 3)
z = x.union(y)
print(z)

{1, 2, 'c', 'b', 3, 'a'}


In [34]:
s1 = {"a", "b" , "c"}
s2 = {1, 2, 3}
s1|=s2    #update
print(s1)

{1, 2, 'c', 'b', 3, 'a'}


#### intersection

In [36]:
s1 = {"app", "bann", "cher"}
s2 = {"goggle", "software", "app"}
s3 = s1.intersection(s2)
print(s3)

{'app'}


In [37]:
s1 = {"app", "bann", "cher"}
s2 = {"goggle", "software", "app"}
s3 = s1&s2
print(s3)

{'app'}


In [38]:
s1 = {"app", 1,  "ban", 0, "cher"}
s2 = {False, "goggle", 1, "app", 2, True}
s3 = s1.intersection(s2)
print(s3)

{False, 1, 'app'}


In [46]:
s1 = {"app", 1,  "ban", 0, "cher"}
s2 = {False, "goggle", 1, "app", 2, True}
s1.intersection_update(s2)
print(s1)

{False, 1, 'app'}


#### difference

In [42]:
s1 = {"app", "bann", "cher"}
s2 = {"goggle", "software", "app"}
s3 = s1-s2
print(s3)

{'cher', 'bann'}


In [43]:
s1 = {"app", 1,  "ban", 0, "cher"}
s2 = {False, "goggle", 1, "app", 2, True}
s3 = s1.difference(s2)
print(s3)

{'cher', 'ban'}


In [45]:
s1 = {"app", 1,  "ban", 0, "cher"}
s2 = {False, "goggle", 1, "app", 2, True}
s1.difference_update(s2)
print(s1)

{'cher', 'ban'}


#### symmetric difference

In [47]:
s1 = {"app", 1,  "ban", 0, "cher"}
s2 = {False, "goggle", 1, "app", 2, True}
s3 = s1.symmetric_difference(s2)
print(s3)

{'cher', 2, 'ban', 'goggle'}


In [49]:
s1 = {"app", 1,  "ban", 0, "cher"}
s2 = {False, "goggle", 1, "app", 2, True}
s3 = s1 ^ s2
print(s3)

{'cher', 2, 'ban', 'goggle'}


In [48]:
s1 = {"app", 1,  "ban", 0, "cher"}
s2 = {False, "goggle", 1, "app", 2, True}
s1.symmetric_difference_update(s2)
print(s1)

{'cher', 'ban', 2, 'goggle'}


# dictionaries

In [1]:
# Dictionaries are used to store data values in key:value pairs.
# A dictionary is a collection which is ordered*, changeable and do not allow duplicates.
# Dictionaries are written with curly brackets, and have keys and values:
country_capitals =	{
  "India": "Delhi",
  "Pakistan": "Kabul",
  "England": "London"
}
print(country_capitals)

{'India': 'Delhi', 'Pakistan': 'Kabul', 'England': 'London'}


In [2]:
country_capitals =	{
  "India": "Delhi",                # Duplicates are not allowed
  "Pakistan": "Kabul",
  "England": "London",
  "India": "haryana"
}
print(country_capitals)

{'India': 'haryana', 'Pakistan': 'Kabul', 'England': 'London'}


In [3]:
country_capitals =	{
  "India": "Delhi",
  "Pakistan": "Kabul",
  "England": "London"
}
print(len(country_capitals))

3


In [4]:
country_capitals =	{
  "India": "Delhi",
  "Pakistan": "Kabul",
  "England": "London"
}
print(type(country_capitals))

<class 'dict'>


In [5]:
d = dict(name = "divya", age = 23, country = "India")
print(d)


{'name': 'divya', 'age': 23, 'country': 'India'}


## access items

In [7]:
country_capitals =	{
  "India": "Delhi",
  "Pakistan": "Kabul",
  "England": "London"
}
x = country_capitals['Pakistan']
print(x)

Kabul


In [9]:
country_capitals =	{
  "India": "Delhi",
  "Pakistan": "Kabul",
  "England": "London"
}
x = country_capitals.get('India')
print(x)

Delhi


### get keys

In [11]:
x = country_capitals.keys()
print(x)

dict_keys(['India', 'Pakistan', 'England'])


In [13]:
car = {
"brand": "Ford",
"model": "Mustang",
"year": 1964
}
x = car.keys()
print(x)                   #before the change
car["color"] = "white"
print(x)                   #after the change

dict_keys(['brand', 'model', 'year'])
dict_keys(['brand', 'model', 'year', 'color'])


### get values

In [12]:
x = country_capitals.values()
print(x)

dict_values(['Delhi', 'Kabul', 'London'])


In [14]:
car = {
"brand": "Ford",
"model": "Mustang",
"year": 1964
}
x = car.values()
print(x)                  #before the change
car["color"] = "white"
print(x)                  #after the change

dict_values(['Ford', 'Mustang', 1964])
dict_values(['Ford', 'Mustang', 1964, 'white'])


### get items

In [15]:
x = country_capitals.items()
print(x)

dict_items([('India', 'Delhi'), ('Pakistan', 'Kabul'), ('England', 'London')])


In [16]:
car = {
"brand": "Ford",
"model": "Mustang",
"year": 1964
}
x = car.items()
print(x)                  #before the change
car["color"] = "white"
print(x)                  #after the change

dict_items([('brand', 'Ford'), ('model', 'Mustang'), ('year', 1964)])
dict_items([('brand', 'Ford'), ('model', 'Mustang'), ('year', 1964), ('color', 'white')])


## change items

### change values

In [19]:
country_capitals =	{
  "India": "Delhi",
  "Pakistan": "Kabul",
  "England": "London"
}
country_capitals['Pakistan'] = "Germany"
print(country_capitals)

{'India': 'Delhi', 'Pakistan': 'Germany', 'England': 'London'}


### update

In [20]:
country_capitals =	{
  "India": "Delhi",
  "Pakistan": "Kabul",
  "England": "London"
}
country_capitals.update({'Pakistan':"Iran"})
print(country_capitals)

{'India': 'Delhi', 'Pakistan': 'Iran', 'England': 'London'}


## add items

In [22]:
car = {
"brand": "Ford",
"model": "Mustang",
"year": 1964
}                  
car["color"] = "white"
print(car)                   

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964, 'color': 'white'}


## remove items

In [26]:
car = {
"brand": "Ford",
"model": "Mustang",
"year": 1964
}                  
car.pop("year")
print(car)                   

{'brand': 'Ford', 'model': 'Mustang'}


In [27]:
car = {
"brand": "Ford",
"model": "Mustang",
"year": 1964
}                  
car.popitem()
print(car)                   

{'brand': 'Ford', 'model': 'Mustang'}


In [28]:
car = {
"brand": "Ford",
"model": "Mustang",
"year": 1964
}                  
del car["model"] 
print(car) 

{'brand': 'Ford', 'year': 1964}


In [31]:
car = {
"brand": "Ford",
"model": "Mustang",
"year": 1964
}                  
del car 

In [32]:
car = {
"brand": "Ford",
"model": "Mustang",
"year": 1964
}                  
car.clear()
print(car) 

{}


## loop dictionaries

In [46]:
car = {
 "brand": "Ford",
 "model": "Mustang",
 "year": 1964
}  
for x in car:
  print(x)

brand
model
year


In [47]:
for x in car:
  print(car[x])

Ford
Mustang
1964


In [48]:
for x in car.values():
  print(x)

Ford
Mustang
1964


In [49]:
for x in car.keys():
  print(x)

brand
model
year


In [50]:
for x in car.items():
  print(x)

('brand', 'Ford')
('model', 'Mustang')
('year', 1964)


In [51]:
for x, y in car.items():
  print(x, y)

brand Ford
model Mustang
year 1964


### copy dictionaries

In [54]:
car = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
newcar = car.copy()
print(newcar)

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964}


In [55]:
car = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
newcar = dict(car)
print(newcar)

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964}


## nested dictionaries

In [56]:
# A dictionary can contain dictionaries, this is called nested dictionaries.
mycar = {
  "car1" : {
    "name" : "wagnor",
    "year" : 1965
  },
  "car2" : {
    "name" : "mustang",
    "year" : 1974
  },
  "car3" : {
    "name" : "ford",
    "year" : 2001
  }
}
print(mycar)

{'car1': {'name': 'wagnor', 'year': 1965}, 'car2': {'name': 'mustang', 'year': 1974}, 'car3': {'name': 'ford', 'year': 2001}}


In [59]:
car1 = {
   "name" : "wagnor",
    "year" : 1965 
}
car2 = {
    "name" : "mustang",
    "year" : 1974 
}
car3 = {
  "name" : "ford",
    "year" : 2001   
}
mycar = {
   "car1" :  car1,
   "car2" :  car2,
   "car3" :  car3
}
print(mycar)

{'car1': {'name': 'wagnor', 'year': 1965}, 'car2': {'name': 'mustang', 'year': 1974}, 'car3': {'name': 'ford', 'year': 2001}}


In [61]:
mycar = {
  "car1" : {
    "name" : "wagnor",
    "year" : 1965
  },
  "car2" : {
    "name" : "mustang",
    "year" : 1974
  },
  "car3" : {
    "name" : "ford",
    "year" : 2001
  }
}
print(mycar["car2"]["name"])
)

mustang


In [67]:
mycar = {
  "car1" : {
    "name" : "wagnor",
    "year" : 1965
  },
  "car2" : {
    "name" : "mustang",
    "year" : 1974
  },
  "car3" : {
    "name" : "ford",
    "year" : 2001
  }
}
for x, obj in mycar.items():
    print(x)
    for y in obj:
     print(y + ':', obj[y])

car1
name: wagnor
year: 1965
car2
name: mustang
year: 1974
car3
name: ford
year: 2001


# If-Else

In [68]:
a = 3
b = 20

if b > a:
  print("b is greater than a")

b is greater than a


### Elif

In [69]:
a = 5
b = 5
if b > a:
  print("b is greater than a")
elif a == b:
  print("a and b are equal")

a and b are equal


## Else

In [70]:
a = 11
b = 3
if b > a:
  print("b is greater than a")
elif a == b:
  print("a and b are equal")
else:
  print("a is greater than b")

a is greater than b


In [73]:
# You can also have an else without the elif:
a = 11
b = 3
if b > a:
  print("b is greater than a")
else:
  print("b is not greater than a")

b is not greater than a


## Short Hand If

In [71]:
# If you have only one statement to execute, you can put it on the same line as the if statement.
a = 20
b = 3
if a > b: print("a is greater than b")

a is greater than b


## Short Hand If- Else

In [75]:
a = 2
b = 33
print("A") if a > b else print("B")

B


In [76]:
a = 2
b = 33
print("A") if a < b else print("B")

A


In [78]:
a = 33
b = 33
print("A") if a >= b else print("B")
# This technique is known as Ternary Operators, or Conditional Expressions.

A


In [79]:
# You can also have multiple else statements on the same line:
a = 330
b = 330
print("A") if a > b else print("=") if a == b else print("B")

=


In [80]:
a = 300
b = 330
print("A") if a > b else print("=") if a == b else print("B")

B


In [82]:
a = 530
b = 330
print("A") if a > b else print("=") if a == b else print("B")

A


## AND

In [83]:
a = 200
b = 33
c = 500
if a > b and c > a:
  print("Both conditions are True")

Both conditions are True


In [93]:
a = 200
b = 33
c = 500
if a < b and c > a:
  print("Both conditions are True")
else:
  print("False")

False


## OR

In [94]:
a = 200
b = 33
c = 500
if a > b or a > c:
  print("At least one of the conditions is True")

At least one of the conditions is True


In [98]:
a = 20
b = 3
c = 1
if a > b and  b > c:
  print("True")

True


## NOT

In [99]:
a = 33
b = 200
if not a > b:
  print("True")

True


## Nested If-Else

In [100]:
x = 55
if x > 10:
  print("Above ten,")
  if x > 20:
    print("and also above 20!")
  else:
    print("but not above 20.")

Above ten,
and also above 20!


In [101]:
x = 15
if x > 10:
  print("Above ten,")
  if x > 20:
    print("and also above 20!")
  else:
    print("but not above 20.")

Above ten,
but not above 20.


# For loop

In [4]:
#A for loop is used for iterating over a sequence (that is either a list, a tuple, a dictionary, a set, or a string).
a = ["abc", "bann", "err"]      #list
for x in a:
  print(x) 

abc
bann
err


In [5]:
a = {"abc", "bann", "err"}      #set
for x in a:
  print(x) 

err
bann
abc


In [6]:
a = ("abc", "bann", "err")      #tuple
for x in a:
  print(x) 

abc
bann
err


In [17]:
dict = {
    "abc":1,
    "bann":2, 
    "err":3
}                  #dict
for x in dict:
 print(dict[x])

1
2
3


## Looping Through a String
Even strings are iterable objects, they contain a sequence of characters:

In [9]:
for x in "abcd":
  print(x)

a
b
c
d


## break statement

In [10]:
# With the break statement we can stop the loop before it has looped through all the items:
a = ["divya", "deswal", "divu"]       #list
for x in a:
  print(x)
  if x == "deswal":
    break

divya
deswal


In [11]:
a = ("divya", "deswal", "divu")      #tuple
for x in a:
  print(x)
  if x == "deswal":
    break

divya
deswal


In [12]:
a = {"divya", "deswal", "divu"}       #set
for x in a:
  print(x)
  if x == "deswal":
    break

deswal


In [15]:
a = {
    "divya":45,
    "deswal":56,
    "divu":78
}                        #dict
for x in a:
  print(a[x])
  if x == "deswal":
    break

45
56


but this time the break comes before the print:

In [22]:
a = ("divya", "deswal", "divu")      #tuple
for x in a:
  if x == "deswal":
    break
  print(x)

divya


In [8]:
a = ["divya", "deswal", "divu"]      #list
for x in a:
  if x == "deswal":
    break
  print(x)

divya


In [6]:
a = {
    "divya":45,
    "deswal":56,
    "divu":78
}                        #dict
for x in a:
  if x == "deswal":
    break
  print(a[x])

45


## The continue Statement
With the continue statement we can stop the current iteration of the loop, and continue with the next:

In [29]:
a = ["divya", "deswal", "divu"]       #list
for x in a:
  if x == "deswal":
    continue
  print(x)

divya
divu


In [30]:
a = ("divya", "deswal", "divu")       #tuple
for x in a:
  if x == "deswal":
    continue
  print(x)

divya
divu


In [31]:
a = {"divya", "deswal", "divu"}       #set
for x in a:
  if x == "deswal":
    continue
  print(x)

divu
divya


In [13]:
a = {
    "divya":45,
    "deswal":56,
    "divu":78
}                        #dict
for x in a.items():
    if x == ("deswal",56):
        continue     
    print(x)


('divya', 45)
('divu', 78)


when print values before continue statement

In [49]:
a = {
    "divya":45,
    "deswal":56,
    "divu":78
}                        #dict
for x in a:
  print(a[x])
  if x == "deswal":
    continue

45
56
78


## The range() Function
To loop through a set of code a specified number of times, we can use the range() function,
The range() function returns a sequence of numbers, starting from 0 by default, and increments by 1 (by default), and ends at a specified number.

In [50]:
for x in range(7):
  print(x)

0
1
2
3
4
5
6


In [51]:
for x in range(6,10):
  print(x)

6
7
8
9


the range() function defaults to increment the sequence by 1, however it is possible to specify the increment value by adding a third parameter:


In [53]:
for x in range(4, 30, 4):
  print(x)

4
8
12
16
20
24
28


## Else in For Loop
The else keyword in a for loop specifies a block of code to be executed when the loop is finished:

In [56]:
for x in range(4):
  print(x)
else:
  print("finish")

0
1
2
3
finish


In [62]:
for x in range(3):
  if x == 2: break
  print(x)
else:
  print("finish")

#If the loop breaks, the else block is not executed.

0
1


## Nested Loops
A nested loop is a loop inside a loop.

The "inner loop" will be executed one time for each iteration of the "outer loop":

In [63]:
a = ["red", "blue", "orange"]  #list
b = ["rohtak", "sonipat", "panipat"]

for x in a:
  for y in b:
    print(x, y)

red rohtak
red sonipat
red panipat
blue rohtak
blue sonipat
blue panipat
orange rohtak
orange sonipat
orange panipat


In [64]:
a = ("red", "blue", "orange")  #tuple
b = ("rohtak", "sonipat", "panipat")

for x in a:
  for y in b:
    print(x, y)

red rohtak
red sonipat
red panipat
blue rohtak
blue sonipat
blue panipat
orange rohtak
orange sonipat
orange panipat


In [65]:
a = {"red", "blue", "orange"}  #set
b = {"rohtak", "sonipat", "panipat"}

for x in a:
  for y in b:
    print(x, y)

red rohtak
red panipat
red sonipat
orange rohtak
orange panipat
orange sonipat
blue rohtak
blue panipat
blue sonipat


In [67]:
a = {
    "red":1,
    "blue":2,
    "orange":3
}                        #dict
b = {
    "rohtak":4,
    "sonipat":5,
    "panipat":6
}

for x in a:
  for y in b:
    print(a[x], b[y])

1 4
1 5
1 6
2 4
2 5
2 6
3 4
3 5
3 6


## The pass Statement
for loops cannot be empty, but if you for some reason have a for loop with no content, put in the pass statement to avoid getting an error.

In [69]:
for x in [4, 9, 2]:
  pass

# The while Loop
With the while loop we can execute a set of statements as long as a condition is true.

In [71]:
i = 1
while i < 10:
  print(i)
  i += 2

1
3
5
7
9


## The break Statement
With the break statement we can stop the loop even if the while condition is true:

In [73]:
i = 1
while i < 9:
  print(i)
  if i == 4:
    break
  i += 1

1
2
3
4


In [77]:
i = 1
while i < 9:
  if i == 4:
    break
  i += 1
print(i)

4


## The continue Statement

In [78]:
i = 0
while i < 9:
  i += 1
  if i == 4:
    continue
  print(i)

1
2
3
5
6
7
8
9


In [80]:
i = 1
while i < 9:
  i += 2
  if i == 4:
    continue
  print(i)

3
5
7
9


## The else Statement
With the else statement we can run a block of code once when the condition no longer is true:

In [2]:
i = 1
while i < 9:
  print(i)
  i += 2
else:
  print(" True ")

1
3
5
7
 True 


# Functions
A function is a block of code which only runs when it is called.

You can pass data, known as parameters, into a function.

In [18]:
def add(a,b):
    c=a+b
    a=a*b
    print(f"addition is {c}")
    print(f"multipication is {a}")
add(5,6)

addition is 11
multipication is 30


In [19]:
add(12,12)

addition is 24
multipication is 144


In [23]:
def asd(a,b):
    for x in a:
        
        for y in b:
            
            print(x, y)
     

In [24]:
a = {"red", "blue", "orange"}  #set
b = {"rohtak", "sonipat", "panipat"}
print(asd(a,b))

blue panipat
blue sonipat
blue rohtak
red panipat
red sonipat
red rohtak
orange panipat
orange sonipat
orange rohtak
None


In [ ]:
x = 55
if x > 10:
  print("Above ten,")
  if x > 20:
    print("and also above 20!")
  else:
    print("but not above 20.")

In [12]:
def number(x):
     if x > 10:
       print("Above ten,")
     if x > 20:
       print("and also above 20!")
     else:
        print("but not above 20.")

In [14]:
x=56
print(number(x))

Above ten,
and also above 20!
None


## Creating a Function
In Python a function is defined using the def keyword:

In [16]:
def fun():
  print("function")

## Calling a Function
To call a function, use the function name followed by parenthesis:

In [18]:
def fun():
  print("function")
fun()

function


## Arguments
Information can be passed into functions as arguments.

Arguments are specified after the function name, inside the parentheses. You can add as many arguments as you want, just separate them with a comma.

In [19]:
def fun(fname): #parameters/variables
  print(fname + " D.d")

fun("Divya") #argument(arg)
fun("Anjali")
fun("Madhu")

Divya D.d
Anjali D.d
Madhu D.d


## Parameters or Arguments?
The terms parameter and argument can be used for the same thing: information that are passed into a function.

From a function's perspective:

A parameter is the variable listed inside the parentheses in the function definition.

An argument is the value that is sent to the function when it is called.

In [21]:
# This function expects 2 arguments, and gets 2 arguments:

def fun(fname, lname):
  print(fname + " " + lname)

fun("Divya", "Deswal")

Divya Deswal


## Arbitrary Arguments, *args
If you do not know how many arguments that will be passed into your function, add a * before the parameter name in the function definition.

This way the function will receive a tuple of arguments, and can access the items accordingly:

In [24]:
def fun(*family):
  print("The biggest family is " + family[1])

fun("Ahuja", "Kapoor", "Goenka")

The biggest family is Kapoor


## Keyword Arguments(kwargs)
You can also send arguments with the key = value syntax.

This way the order of the arguments does not matter.



In [26]:
def fun(family1,family2,family3):
  print("The biggest family is " + family3)

fun(family1="Ahuja", family2="Kapoor", family3="Goenka")

The biggest family is Goenka


## Arbitrary Keyword Arguments, **kwargs
If you do not know how many keyword arguments that will be passed into your function, add two asterisk: ** before the parameter name in the function definition.

In [31]:
def fun(**family):
  print("The biggest family is " + family["family1"])

fun(family1="Ahuja", family2="Kapoor", family3="Goenka")

The biggest family is Ahuja


## Default Parameter Value

In [32]:
def fun(city = "Jaipur"):
  print("I am from " + city)

fun("Sonipat")
fun("Rohtak")
fun()
fun("Udaipur")

I am from Sonipat
I am from Rohtak
I am from Jaipur
I am from Udaipur


In [33]:
def fun(city = "Jaipur"):
  print("I am from " + city)

fun("Sonipat")
fun("Rohtak")
fun("Palwal")
fun("Udaipur")

I am from Sonipat
I am from Rohtak
I am from Palwal
I am from Udaipur


In [34]:
def fun(city = "Jaipur"):
  print("I am from " + city)

fun("Sonipat")
fun()
fun("Rohtak")
fun("Palwal")
fun("Udaipur")

I am from Sonipat
I am from Jaipur
I am from Rohtak
I am from Palwal
I am from Udaipur


## Passing a List as an Argument
You can send any data types of argument to a function (string, number, list, dictionary etc.), and it will be treated as the same data type inside the function.

In [35]:
def fun(a):
  for x in a:
    print(x)
                                   #list
b = ["app", "bann", "err"]

fun(b)


app
bann
err


In [36]:
def fun(a):
  for x in a:
    print(x)

b = {"app", "bann", "err"} #set

fun(b)


app
err
bann


In [37]:
def fun(a):
  for x in a:
    print(x)    #tuple

b = ("app", "bann", "err")

fun(b)


app
bann
err


In [41]:
def fun(a):
  for x in a:  #dict
    print(x)

b = {
    "app":1,
    "bann":2,
    "err":3
}

fun([b])


{'app': 1, 'bann': 2, 'err': 3}


## Return Values
To let a function return a value, use the return statement:

In [43]:
def fun(x):
  return 5 * x + 3 / 2

print(fun(3))
print(fun(5))
print(fun(9))

16.5
26.5
46.5


## Positional-Only Arguments
You can specify that a function can have ONLY positional arguments, or ONLY keyword arguments.

To specify that a function can have only positional arguments, add , / after the arguments:

In [44]:
def fun(x, /):
  print(x)

fun(11)

11


In [45]:
# Without the , / you are actually allowed to use keyword arguments even if the function expects positional arguments:

In [46]:
def fun(x):
  print(x)

fun(x=11)

11


## Keyword-Only Arguments
To specify that a function can have only keyword arguments, add *, before the arguments:

In [48]:
def fun(*,x):
  print(x)

fun(x=81)

81


In [49]:
# Without the *, you are allowed to use positionale arguments even if the function expects keyword arguments:
def fun(x):
  print(x)

fun(x=81)

81


## Combine Positional-Only and Keyword-Only
You can combine the two argument types in the same function.

Any argument before the / , are positional-only, and any argument after the *, are keyword-only.

In [50]:
def fun(a, b, /, *, c, d,e):
  print(a * b / c + d - e)

fun(15, 6, c = 7, d = 8,e =10)

10.857142857142858


## Recursion
Python also accepts function recursion, which means a defined function can call itself.

In [52]:
def rec(x):
  if(x > 1):
    a = x + rec(x - 1)
    print(a)
  else:
    a = 0
  return a

rec(0)

0

In [53]:
def rec(x):
  if(x > 1):
    a = x + rec(x - 1)
    print(a)
  else:
    a = 0
  return a

rec(5)

2
5
9
14


14

# lambda

In [1]:
#A lambda function is a small anonymous function.
#A lambda function can take any number of arguments, but can only have one expression.
x = lambda a : a + 13
print(x(6))

19


In [2]:
x = lambda a, b : a * b
print(x(9, 6))

54


In [3]:
x = lambda a, b, c : a + b + c
print(x(5, 6, 9))

20


In [4]:
def myfunc(n):
  return lambda a : a * n

In [5]:
def func(n):
  return lambda a : a * n
m = func(2)
print(m(19))

38


In [6]:
def func(n):
  return lambda a : a * n

d = func(2)
t = func(3)

print(d(16))
print(t(11))

32
33


# What is a Module?
Consider a module to be the same as a code library.

A file containing a set of functions you want to include in your application.

In [14]:
def greeting(name):
  print("Hello, " + name)

person1 = {
  "name": "John",
  "age": 36,
  "country": "Norway"
}

# Datetime

In [15]:
import datetime

x = datetime.datetime.now()
print(x)


2024-10-15 09:14:11.261895


In [16]:
import datetime

x = datetime.datetime.now()

print(x.year)
print(x.strftime("%A"))


2024
Tuesday


In [17]:
import datetime

x = datetime.datetime(2020, 5, 17)

print(x)

2020-05-17 00:00:00


In [19]:
import datetime
x = datetime.datetime.now()
print(x.strftime("%w"))

2


In [20]:
import datetime
x = datetime.datetime.now()
print(x.strftime("%d"))

15


In [21]:
import datetime
x = datetime.datetime.now()
print(x.strftime("%H"))

09


In [23]:
import datetime
x = datetime.datetime.now()
print(x.strftime("%S"))

11


In [24]:
import datetime
x = datetime.datetime.now()
print(x.strftime("%p"))

AM


In [25]:
import datetime
x = datetime.datetime.now()
print(x.strftime("%y"))

24


In [26]:
import datetime
x = datetime.datetime.now()
print(x.strftime("%M"))

19


# Built-in Math Functions
The min() and max() functions can be used to find the lowest or highest value in an iterable:

In [28]:
x = min(8, 40, 55)
y = max(55, 80, 15)
print(x)
print(y)

8
80


In [30]:
#The abs() function returns the absolute (positive) value of the specified number:
x = abs(-9.05)
print(x)

9.05


In [32]:
# The pow(x, y) function returns the value of x to the power of y (xy).
x = pow(5, 8)
print(x)

390625


## The Math Module
Python has also a built-in module called math, which extends the list of mathematical functions.

To use it, you must import the math module:

import math

In [35]:
#The math.sqrt() method for example, returns the square root of a number:
import math
x = math.sqrt(125)
print(x)

11.180339887498949


In [36]:
# The math.ceil() method rounds a number upwards to its nearest integer, and 
#the math.floor() method rounds a number downwards to its nearest integer, and returns the result:
import math
x = math.ceil(4.4)
y = math.floor(4.4)
print(x) 
print(y) 

5
4


In [37]:
# The math.pi constant, returns the value of PI (3.14...):
import math
x = math.pi
print(x)

3.141592653589793


# MODULE REFERENCE

## Math Module
Python has a built-in module that you can use for mathematical tasks.

The math module has a set of methods and constants.

In [ ]:
#The math.acos() method returns the arc cosine value of a number.
#Note: The parameter passed in math.acos() must lie between -1 to 1.
#Tip: math.acos(-1) will return the value of PI.
#Syntax
#math.acos(x)

In [38]:
import math

# Return the arc cosine of numbers
print(math.acos(0.55))
print(math.acos(-0.55))
print(math.acos(0))
print(math.acos(1))
print(math.acos(-1))

0.9884320889261531
2.15316056466364
1.5707963267948966
0.0
3.141592653589793


In [40]:
#The math.prod() method returns the product of the elements from the given iterable.
#Syntax
#math.prod(iterable, start)
import math
sequence = (2, 6, 2)
print(math.prod(sequence))

24


In [41]:
#The math.fsum() method returns the sum of all items in any iterable (tuples, arrays, lists, etc.).
#Syntax
#math.fsum(iterable)
import math
print(math.fsum([1, 2, 3, 4, 5]))
print(math.fsum([100, 400, 340, 500]))
print(math.fsum([1.7, 0.3, 1.5, 4.5]))

15.0
1340.0
8.0


In [42]:
import math
print(math.factorial(9))
print(math.factorial(6))
print(math.factorial(12))

362880
720
479001600


In [43]:
import math
print(math.log(2.7183))
print(math.log(2))
print(math.log(1))

1.0000066849139877
0.6931471805599453
0.0


## cmath Module

In [1]:
#The methods in this module accepts int, float, and complex numbers. 
#It even accepts Python objects that has a __complex__() or __float__() method.
#The cmath.acos() method returns the arc cosine of a complex number.
#There are two branch cuts:
#Extends right from 1 along the real axis to ∞
#Extends left from -1 along the real axis to -∞.

In [2]:
import cmath  
print (cmath.sqrt(2 + 3j))
print (cmath.sqrt(15))

(1.6741492280355401+0.8959774761298381j)
(3.872983346207417+0j)


In [3]:
import cmath
print (cmath.pi)

3.141592653589793


In [4]:
import cmath
#find whether a complex number is infinite or not
print (cmath.isinf(complex(10 + float('inf'))))
print (cmath.isinf(11 + 4j))

True
False


# statistics Module
Python has a built-in module that you can use to calculate mathematical statistics of numeric data.

In [5]:
# The statistics.harmonic_mean() method calculates the harmonic mean (central location) of the given data set.
#Harmonic mean = The reciprocal of the arithmetic mean() of the reciprocals of the data.
#The harmonic mean is calculated as follows:
#If you have four values (a, b, c and d) - it will be equivalent to 4 / (1/a + 1/b + 1/c + 1/d).
#Syntax
#statistics.harmonic_mean(data)

In [6]:
import statistics
print(statistics.harmonic_mean([40, 60, 80]))
print(statistics.harmonic_mean([10, 30, 50, 70, 90]))

55.38461538461538
27.97513321492007


In [7]:
import statistics
print(statistics.mean([1, 3, 5, 7, 9, 11, 13]))
print(statistics.mean([1, 3, 5, 7, 9, 11]))
print(statistics.mean([-11, 5.5, -3.4, 7.1, -9, 22]))

7
6
1.8666666666666667


In [8]:
import statistics
print(statistics.median([1, 3, 5, 7, 9, 11, 13]))
print(statistics.mode([1, 3, 5, 7, 9, 11]))
print(statistics.variance([-11, 5.5, -3.4, 7.1, -9, 22]))

7
1
151.46266666666668


In [9]:
#The statistics.pstdev() method calculates the standard deviation from an entire population.
#Standard deviation is a measure of how spread out the numbers are.
#A large standard deviation indicates that the data is spread out, - a small standard deviation indicates that the data is clustered closely around the mean.
#Tip: Standard deviation is (unlike the Variance) expressed in the same units as the data.
#Tip: Standard deviation is the square root of sample variance.

In [10]:
print(statistics.pstdev([1, 3, 5, 7, 9, 11]))
print(statistics.pvariance([2, 2.5, 1.25, 3.1, 1.75, 2.8]))
print(statistics.median_grouped([-11, 5.5, -3.4, 7.1]))
print(statistics.stdev([1, 30, 50, 100]))

3.415650255319866
0.3997222222222222
5.0
41.67633221226007


# PIP

In [ ]:
#PIP is a package manager for Python packages, or modules if you like.
#What is a Package?
#A package contains all the files you need for a module.
#Modules are Python code libraries you can include in your project.
#Check if PIP is Installed
#Navigate your command line to the location of Python's script directory, and type the following:
#Check PIP version:
#C:\Users\Your Name\AppData\Local\Programs\Python\Python36-32\Scripts>pip --version
#Install PIP
#If you do not have PIP installed, you can download and install it from this page: https://pypi.org/project/pip/
#Download a Package
#Downloading a package is very easy.
#Open the command line interface and tell PIP to download the package you want.
#Navigate your command line to the location of Python's script directory, and type the following:
#Example
#Download a package named "camelcase":
#C:\Users\Your Name\AppData\Local\Programs\Python\Python36-32\Scripts>pip install

# Try Except
The try block lets you test a block of code for errors.

The except block lets you handle the error.

The else block lets you execute code when there is no error.

The finally block lets you execute code, regardless of the result of the try- and except blocks.



## Exception Handling
When an error occurs, or exception as we call it, Python will normally stop and generate an error message.

These exceptions can be handled using the try statement:

In [11]:
#The try block will generate an exception, because x is not defined:
try:
  print(x)
except:
  print("An exception occurred")

An exception occurred


In [ ]:
#Without the try block, the program will crash and raise an error:

## Many Exceptions
You can define as many exception blocks as you want, e.g. if you want to execute a special block of code for a special kind of error:

In [12]:
try:
  print(x)
except NameError:
  print("Variable x is not defined")
except:
  print("Something else went wrong")

Variable x is not defined


## Else
You can use the else keyword to define a block of code to be executed if no errors were raised:

In [13]:
try:
  print("Hello")
except:
  print("Something went wrong")
else:
  print("Nothing went wrong")

Hello
Nothing went wrong


## Finally
The finally block, if specified, will be executed regardless if the try block raises an error or not.

In [14]:
try:
  print(x)
except:
  print("Something went wrong")
finally:
  print("The 'try except' is finished")

Something went wrong
The 'try except' is finished


## User Input
Python allows for user input.

That means we are able to ask the user for input.

The method is a bit different in Python 3.6 than Python 2.7.

Python 3.6 uses the input() method.

Python 2.7 uses the raw_input() method.

In [17]:
username = input("Enter name:")
print("name is: " + username)

Enter name: dd


name is: dd


## String Formatting

### Placeholders and Modifiers
To format values in an f-string, add placeholders {}, a placeholder can contain variables, operations, functions, and modifiers to format the value.

In [18]:
price = 10
txt = f"The price is {price} dollars"
print(txt)

The price is 10 dollars


In [3]:
#A placeholder can also include a modifier to format the value.
#A modifier is included by adding a colon : followed by a legal formatting type, like .2f which means fixed point number with 2 decimals:
price = 19
txt = f"The price is {price:.2f} dollars"
print(txt)

The price is 19.00 dollars


# Perform Operations in F-Strings
You can perform Python operations inside the placeholders.
You can do math operations:

In [4]:
#Perform a math operation in the placeholder, and return the result:
txt = f"The price is {20 * 59} dollars"
print(txt)

The price is 1180 dollars


In [5]:
price = 59
tax = 0.25
txt = f"The price is {price + (price * tax)} dollars"
print(txt)

The price is 73.75 dollars


In [6]:
#You can perform if...else statements inside the placeholders:
price = 49
txt = f"It is very {'Expensive' if price>50 else 'Cheap'}"
print(txt)

It is very Cheap


# Execute Functions in F-Strings
You can execute functions inside the placeholder:

In [7]:
#Use the string method upper()to convert a value into upper case letters:
fruit = "apples"
txt = f"I love {fruit.upper()}"
print(txt)

I love APPLES


In [8]:
#The function does not have to be a built-in Python method, you can create your own functions and use them:
#Create a function that converts feet into meters:
def myconverter(x):
  return x * 0.3048

txt = f"The plane is flying at a {myconverter(30000)} meter altitude"
print(txt)

The plane is flying at a 9144.0 meter altitude


# More Modifiers

In [9]:
#Use "," to add a comma as a thousand separator:
txt = f"The universe is {13800000000:,} years old."
print(txt)

The universe is 13,800,000,000 years old.


In [10]:
txt = f"The universe is {13800000000:_} years old."
print(txt)

The universe is 13_800_000_000 years old.


In [11]:
#Use "b" to convert the number into binary format:
txt = f"The binary version of 5 is {5:b}"
print(txt)

The binary version of 5 is 101


In [12]:
#Use "%" to convert the number into a percentage format:
txt = f"You scored {0.25:%}"
print(txt)

#Or, without any decimals:
txt = f"You scored {0.25:.0%}"
print(txt)

You scored 25.000000%
You scored 25%


# File Handling
The key function for working with files in Python is the open() function.

The open() function takes two parameters; filename, and mode.

There are four different methods (modes) for opening a file:

"r" - Read - Default value. Opens a file for reading, error if the file does not exist

"a" - Append - Opens a file for appending, creates the file if it does not exist

"w" - Write - Opens a file for writing, creates the file if it does not exist

"x" - Create - Creates the specified file, returns an error if the file exists

In [2]:
f = open("untitled.txt","r")
print(f.read())

The key function for working with files in Python is the open() function.

The open() function takes two parameters; filename, and mode.

There are four different methods (modes) for opening a file:


In [15]:
f = open("untitled1.txt","w")

# class

### Create a Class


In [2]:
class Policy:
  x = 5
print(Policy)

<class '__main__.Policy'>


### Create Object

In [3]:
p1 = Policy()
print(p1.x)

5


### The __init__() Function

In [4]:
#Create a class named Person, use the __init__() function to assign values for name and age:

class Person:
  def __init__(self, name, age):
    self.name = name
    self.age = age

p1 = Person("Abraham", 46)
print(p1.name)
print(p1.age)

Abraham
46


### The __str__() Function

In [5]:
#The string representation of an object WITH the __str__() function:

class Person:
  def __init__(self, name, age):
    self.name = name
    self.age = age

  def __str__(self):
    return f"{self.name}({self.age})"

p1 = Person("Abraham", 46)
print(p1)

Abraham(46)


### Object Methods
Objects can also contain methods. Methods in objects are functions that belong to the object.

Let us create a method in the Person class:

In [6]:
#Insert a function that prints a greeting, and execute it on the p1 object:

class Person:
  def __init__(self, name, age):
    self.name = name
    self.age = age

  def myfunc(self):
    print("Hello my name is " + self.name)

p1 = Person("Abraham", 46)
p1.myfunc()

Hello my name is Abraham


### The self Parameter
The self parameter is a reference to the current instance of the class, and is used to access variables that belong to the class.

In [7]:
class Person:
  def __init__(mysillyobject, name, age):
    mysillyobject.name = name
    mysillyobject.age = age

  def myfunc(abc):
    print("Hello my name is " + abc.name)

p1 = Person("Abraham", 46)
p1.myfunc()

Hello my name is Abraham


### Modify Object Properties

In [9]:
p1.age = 40
print(p1.age)

40


### Delete Object Properties

In [16]:
del p1.age

NameError: name 'p1' is not defined

In [15]:
del p1

### The pass Statement

In [17]:
class Person:
  pass

# Inheritance
Inheritance allows us to define a class that inherits all the methods and properties from another class.

Parent class is the class being inherited from, also called base class.

Child class is the class that inherits from another class, also called derived class.

### Create a Parent Class


In [1]:
class Person:
  def __init__(self, fname, lname):
    self.firstname = fname
    self.lastname = lname

  def printname(self):
    print(self.firstname, self.lastname)

x = Person("divya", "deswal")
x.printname()

divya deswal


### Create a Child Class
To create a class that inherits the functionality from another class, send the parent class as a parameter when creating the child class:

In [2]:
class Student(Person):
  pass

In [4]:
x = Student("divya", "deswal")
x.printname()

divya deswal


### Add the __init__() Function

In [5]:
#The __init__() function is called automatically every time the class is being used to create a new object.
class Person:
  def __init__(self, fname, lname):
    self.firstname = fname
    self.lastname = lname

  def printname(self):
    print(self.firstname, self.lastname)

class Student(Person):
  def __init__(self, fname, lname):
    Person.__init__(self, fname, lname)

x = Student("divya", "deswal")
x.printname()

divya deswal


In [6]:
#Use the super() Function Python also has a super() function that will make the child class inherit all the methods and properties from its parent:
class Person:
  def __init__(self, fname, lname):
    self.firstname = fname
    self.lastname = lname

  def printname(self):
    print(self.firstname, self.lastname)

class Student(Person):
  def __init__(self, fname, lname):
    super().__init__(fname, lname)

x = Student("divya", "deswal")
x.printname()

divya deswal


### Add Properties

In [7]:
class Person:
  def __init__(self, fname, lname):
    self.firstname = fname
    self.lastname = lname

  def printname(self):
    print(self.firstname, self.lastname)

class Student(Person):
  def __init__(self, fname, lname):
    super().__init__(fname, lname)
    self.graduationyear = 2019

x = Student("divya", "deswal")
print(x.graduationyear)

2019


In [8]:
class Person:
  def __init__(self, fname, lname):
    self.firstname = fname
    self.lastname = lname

  def printname(self):
    print(self.firstname, self.lastname)

class Student(Person):
  def __init__(self, fname, lname, year):
    super().__init__(fname, lname)
    self.graduationyear = year

x = Student("divya", "deswal", 2019)
print(x.graduationyear)

2019


### Add Methods

In [9]:
class Person:
  def __init__(self, fname, lname):
    self.firstname = fname
    self.lastname = lname

  def printname(self):
    print(self.firstname, self.lastname)

class Student(Person):
  def __init__(self, fname, lname, year):
    super().__init__(fname, lname)
    self.graduationyear = year

  def welcome(self):
    print("Welcome", self.firstname, self.lastname, "to the class of", self.graduationyear)

x = Student("divya", "deswal", 2024)
x.welcome()

Welcome divya deswal to the class of 2024


# Numpy

NumPy is a Python library used for working with arrays.
It also has functions for working in domain of linear algebra, fourier transform, and matrices.
In Python we have lists that serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

Why is NumPy Faster Than Lists?
NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.
This behavior is called locality of reference in computer science.
This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.                     

                    

NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++.



In [7]:
import numpy
arr = numpy.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


NumPy is usually imported under the np alias.

alias: In Python alias are an alternate name for referring to the same thing.

Create an alias with the as keyword while importing:



In [8]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


Checking NumPy Version
The version string is stored under __version__ attribute.

In [9]:
import numpy as np
print(np.__version__)

1.26.4


## NumPy Creating Arrays

Create a NumPy ndarray Object

NumPy is used to work with arrays. The array object in NumPy is called ndarray.
We can create a NumPy ndarray object by using the array() function.

In [10]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [11]:
#To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:
import numpy as np
arr = np.array((1, 2, 3, 4, 5))
print(arr)

[1 2 3 4 5]


Dimensions in Arrays

A dimension in arrays is one level of array depth (nested arrays).

nested array: are arrays that have arrays as their elements.

In [12]:
#0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.
import numpy as np
arr = np.array(2)
print(arr)

2


In [13]:
#1-D Arrays
#An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [14]:
#2-D Arrays
#An array that has 1-D arrays as its elements is called a 2-D array.
#These are often used to represent matrix or 2nd order tensors.
#NumPy has a whole sub module dedicated towards matrix operations called numpy.mat
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [15]:
#3-D arrays
#An array that has 2-D arrays (matrices) as its elements is called 3-D array.
#These are often used to represent a 3rd order tensor.
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [19]:
#Check Number of Dimensions?
#NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.
import numpy as np
a = np.array(4)
a1 = np.array([5])
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a.ndim)
print(a1.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
1
2
3


In [20]:
#Higher Dimensional Arrays
#An array can have any number of dimensions.
#When the array is created, you can define the number of dimensions by using the ndmin argument.
import numpy as np
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


## NumPy Array Indexing


In [21]:
#Access 1-D Array Elements
#Array indexing is the same as accessing an array element.
#You can access an array element by referring to its index number.
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr[0])

1


In [22]:
print(arr[3])

4


In [23]:
#Get third and fourth elements from the following array and add them.
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr[2] + arr[3])

7


In [25]:
print(arr[0] + arr[1])

3


In [26]:
#Access 2-D Arrays
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [28]:
print('2nd element on 2nd row: ', arr[1, 1])

2nd element on 2nd row:  7


In [29]:
print('5th element on 1st row: ', arr[0, 4])

5th element on 1st row:  5


In [30]:
#Access 3-D Arrays
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2])

6


In [31]:
print(arr[1, 1, 2])

12


In [33]:
print(arr[1, 0, 0])

7


In [34]:
# Negative Indexing
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


## NumPy Array Slicing

Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

In [35]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

[2 3 4 5]


In [36]:
print(arr[4:])

[5 6 7]


In [37]:
print(arr[1:])

[2 3 4 5 6 7]


In [38]:
print(arr[:5])

[1 2 3 4 5]


In [39]:
print(arr[-3:-1])

[5 6]


In [40]:
#STEP
#Use the step value to determine the step of the slicing:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])

[2 4]


In [41]:
print(arr[::2])

[1 3 5 7]


In [42]:
#Slicing 2-D Arrays
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

[7 8 9]


In [43]:
print(arr[0:2, 2])

[3 8]


In [44]:
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [45]:
print(arr[0:2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
