### 1. Array Creation
Create a 1D array of numbers from 0 to 9.
Create a 2D array of shape (3, 3) filled with ones.
Create an array of 10 random floats between 0 and 1.

In [6]:
import numpy as np
arr_1d = np.array(range(10))
print(arr_1d)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
import numpy as np
arr_2d = np.array([1, 1, 1, 1, 1, 1, 1, 1, 1])
newarr_2d = arr_2d.reshape(3, 3)
print(newarr_2d)


[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [3]:
import numpy as np
x = np.random.rand(10)
x

array([0.81070497, 0.69203502, 0.51926417, 0.01379327, 0.34462914,
       0.75571672, 0.07888661, 0.61455237, 0.30760927, 0.80747748])

### 2. Array Indexing and Slicing
Extract the first three elements from an array [5, 10, 15, 20, 25].
Access elements from a 2D array [[1, 2, 3], [4, 5, 6], [7, 8, 9]] to
get the value 5.
Reverse an array [0, 1, 2, 3, 4, 5].

In [15]:
import numpy as np
x = np.array([5, 10, 15, 20, 25])
print(x[:3])

y = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(y[1, 1]) 

z = np.array([0, 1, 2, 3, 4, 5])
print(z[::-1])

[ 5 10 15]
5
[5 4 3 2 1 0]


### 3. Array Manipulation
Create an array of shape (4, 4) and reshape it to (2, 8).
Concatenate two arrays [1, 2, 3] and [4, 5, 6].

In [18]:
import numpy as np
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])
y = x.reshape(2, 8)
print(y)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


In [19]:
import numpy as np
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
z = np.concatenate((x,y))
print(z)

[1 2 3 4 5 6]


### 4. Mathematical Operations
Add, subtract, multiply, and divide two arrays [1, 2, 3] and [4, 5, 6].

Find the mean, median, and standard deviation of an array [1, 2, 3, 4, 5].

Find the dot product of two arrays [1, 2] and [3, 4].

In [21]:
import numpy as np
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])
addition = np.add(a1, a2)
subtraction = np.subtract(a1, a2)
multiplication = np.multiply(a1, a2)
division = np.divide(a1, a2)
print(addition) 
print(subtraction) 
print(multiplication)
print(division)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [22]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])
mean = np.mean(a)
median = np.median(a)
std_dev = np.std(a)
print(mean)
print(median)
print(std_dev)

3.0
3.0
1.4142135623730951


In [23]:
import numpy as np
a1 = np.array([1, 2])
a2 = np.array([3, 4])
dot_product = np.dot(a1, a2)
print(dot_product)

11


### 5. Array Conditions and Filtering
Extract all even numbers from an array [0, 1, 2, 3, 4, 5, 6, 7, 8, 9].

Replace all odd numbers in an array [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] with 
-1.


In [3]:
import numpy as np

a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
even = a[a % 2 == 0]
print(even)

[0 2 4 6 8]


In [12]:
import numpy as np
x = np.array([0,1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])
odd=x[x%2==1]
print(odd)
x[odd]=-1
print(x)

[ 1  3  5  7  9 11 13 15]
[ 0 -1  2 -1  4 -1  6 -1  8 -1 10 -1 12 -1 14 -1 16]


### 6. Matrix Operations
Multiply two matrices [[1, 2], [3, 4]] and [[5, 6], [7, 8]].

Find the inverse of a matrix [[1, 2], [3, 4]].

In [9]:
import numpy as np
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])
m = np.dot(m1, m2)
print("M1:")
print(m1)
print("\nM2:")
print(m2)
print("\nProduct of M1 and M2:")
print(m)


M1:
[[1 2]
 [3 4]]

M2:
[[5 6]
 [7 8]]

Product of M1 and M2:
[[19 22]
 [43 50]]


In [12]:
import numpy as np
m = np.array([[1, 2], [3, 4]])
m_inv = np.linalg.inv(m)
print("Inverse of the Matrix:")
print(m_inv)

Inverse of the Matrix:
[[-2.   1. ]
 [ 1.5 -0.5]]


### 7. Statistical Operations
Compute the maximum, minimum, and sum of an array [1, 2, 3, 4, 5]
along the first axis.
    
Use np.where() to find the indices of elements greater than 3 in an array [1, 
2, 3, 4, 5].

In [13]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])
max_value = np.max(a)
min_value = np.min(a)
sum_value = np.sum(a)

indices_greater_than_3 = np.where(a > 3)
print("Array:", a)
print("Maximum value:", max_value)
print("Minimum value:", min_value)
print("Sum of elements:", sum_value)
print("Indices of elements greater than 3:", indices_greater_than_3[0])


Array: [1 2 3 4 5]
Maximum value: 5
Minimum value: 1
Sum of elements: 15
Indices of elements greater than 3: [3 4]


### 8. Broadcasting
Subtract a 1D array [1, 2, 3] from a 2D array [[4, 5, 6], [7, 8, 9]]
using broadcasting.

In [14]:
import numpy as np
a_2d = np.array([[4, 5, 6], [7, 8, 9]])
a_1d = np.array([1, 2, 3])
a = a_2d - a_1d
print("2D Array:")
print(a_2d)
print("\n1D Array:")
print(a_1d)
print("\nResult after broadcasting subtraction:")
print(a)

2D Array:
[[4 5 6]
 [7 8 9]]

1D Array:
[1 2 3]

Result after broadcasting subtraction:
[[3 3 3]
 [6 6 6]]


### 9. Advanced Array Manipulation
Create a 3D array of shape (3, 3, 3) filled with random values and find the index 
of the maximum value.
    
Split an array [1, 2, 3, 4, 5, 6] into three sub-arrays.

In [22]:
import numpy as np
a = np.random.rand(3, 3, 3)
print(a)

[[[0.10518702 0.03233413 0.74925611]
  [0.85502897 0.33254437 0.28138012]
  [0.85424171 0.1082694  0.58124067]]

 [[0.8741435  0.57367187 0.35552632]
  [0.29530844 0.65635283 0.59906754]
  [0.10478873 0.5952511  0.55892729]]

 [[0.39782624 0.59996341 0.20870229]
  [0.20193063 0.56823433 0.71494233]
  [0.27349795 0.26410037 0.92947927]]]


In [23]:
split_a = np.array([1, 2, 3, 4, 5, 6])
print(split_a)

[1 2 3 4 5 6]


In [20]:
sub_arrays = np.split(split_a, 3)
print(sub_arrays)

[array([1, 2]), array([3, 4]), array([5, 6])]


### 10.Performance Optimization
Compare the performance of a simple loop-based summation with NumPy’s 
np.sum() using timeit.
    
Use vectorized operations to calculate the square of numbers from 0 to 9.

In [14]:
import numpy as np
n = np.arange(10)
x = n ** 2
print(x)

[ 0  1  4  9 16 25 36 49 64 81]


### 11.Handling Missing Data
Create an array with some np.nan values and calculate the mean, ignoring the 
nan values.

Replace nan values with the median of the array.

In [1]:
import numpy as np
arr=np.array([1,2,np.nan,5,7,np.nan])
mean=np.nanmean(arr)
mean

3.75

In [2]:
median=np.nanmedian(arr)
median

3.5

In [3]:
a=np.where(np.isnan(arr))
a
arr[a]=median
arr

array([1. , 2. , 3.5, 5. , 7. , 3.5])

### 12.Stock Market Analysis
Given daily closing prices of a stock for a month, compute the average, highest, 
and lowest closing prices.

Calculate the moving average of the stock price over a 5-day window using 
NumPy.

In [2]:
import numpy as np
closing_prices = [
    10, 12, 15, 17, 11, 18, 17, 19, 15, 18, 
    13, 16, 18, 20, 21, 19, 11, 18, 19, 12, 
    12, 24, 25, 23, 12, 22, 14, 13, 15, 17
]

avg_price = np.mean(closing_prices)
hst_price = np.max(closing_prices)
lst_price = np.min(closing_prices)
print(f"Average Closing Price: {avg_price}")
print(f"Highest Closing Price: {hst_price}")
print(f"Lowest Closing Price: {lst_price}")

Average Closing Price: 16.533333333333335
Highest Closing Price: 25
Lowest Closing Price: 10


In [4]:
mov_avg = [np.mean(closing_prices[i:i+5]) 
 for i in range(len(closing_prices) - 4)]
print(mov_avg)

[13.0, 14.6, 15.6, 16.4, 16.0, 17.4, 16.4, 16.2, 16.0, 17.0, 17.6, 18.8, 17.8, 17.8, 17.6, 15.8, 14.4, 17.0, 18.4, 19.2, 19.2, 21.2, 19.2, 16.8, 15.2, 16.2]


### 13.Weather Data Analysis
Given an array of daily temperatures, find the number of days with temperatures 
above the monthly average.

Identify the hottest and coldest days in a year-long temperature dataset

In [9]:
import numpy as np
temp = np.array([15, 20, 18, 22, 25, 11, 20, 32, 10, 15, 27, 20, 15, 18, 22, 25, 28, 31, 33, 
    29, 27, 26, 24, 22, 20, 15, 10, 5, 2, 1])  

monthly_avg = np.mean(temp) 
days_above_avg = np.sum(temp > monthly_avg)  

print(f"Monthly Average Temperature: {monthly_avg:.2f}°C")
print(f"Number of Days Above Monthly Average: {days_above_avg}")

hottest_temp = np.max(temp)  
coldest_temp = np.min(temp)  
hottest_day = np.where(temp == hottest_temp)[0][0] + 1
coldest_day = np.where(temp == coldest_temp)[0][0] + 1  

print(f"Hottest Temp: {hottest_temp}°C on Day {hottest_day}")
print(f"Coldest Temp: {coldest_temp}°C on Day {coldest_day}")


Monthly Average Temperature: 19.60°C
Number of Days Above Monthly Average: 18
Hottest Temp: 33°C on Day 19
Coldest Temp: 1°C on Day 30


### 14.Sports Performance Metrics
Given the scores of a player in multiple matches, compute the player's average 
score, highest score, and standard deviation.

Simulate the result of a game using random values to predict the probability of 
winning, losing, or drawing.

In [3]:
import numpy as np
s = np.array([101, 142, 64, 121, 110, 70, 132, 136, 124, 124])
avg = np.mean(s)
highest = np.max(s)
std_dev = np.std(s)
result = np.random.choice(['Win', 'Lose', 'Draw'], p=[0.5, 0.3, 0.2])
print(f"Scores: {s}")
print(f"Average Score: {avg}")
print(f"Highest Score: {highest}")
print(f"Standard Deviation: {std_dev}")
print(f"Game Outcome: {result}")

Scores: [101 142  64 121 110  70 132 136 124 124]
Average Score: 112.4
Highest Score: 142
Standard Deviation: 25.370061095708856
Game Outcome: Win


### 15. Recommendation Systems
Given user ratings for movies in a 2D array format, calculate the average rating 
for each movie

In [4]:
import numpy as np
r = np.array([
    [4, 5, 3, 0],
    [5, 0, 4, 3],
    [3, 4, 0, 2],
    [0, 5, 4, 4]
])
r_with_nan = np.where(r == 0, np.nan, r)
avg_r = np.nanmean(r_with_nan, axis=0)
r, avg_r

(array([[4, 5, 3, 0],
        [5, 0, 4, 3],
        [3, 4, 0, 2],
        [0, 5, 4, 4]]),
 array([4.        , 4.66666667, 3.66666667, 3.        ]))